[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.33"
allow_internal_expect_revert = true
fs_permissions = [{ access = "read-write", path = "." }]
optimizer = true
optimizer_runs = 1000
verbosity = 3
via_ir = true

[fuzz]
runs = 5000
max_test_rejects = 150000

[lint]
lint_on_build = false

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
optimism-sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
bsc = "${BSC_RPC_URL}"
bsc-testnet = "${BSC_TESTNET_RPC_URL}"
unichain = "${UNICHAIN_RPC_URL}"
unichain-sepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
polygon-amoy = "${POLYGON_AMOY_RPC_URL}"
worldchain = "${WORLDCHAIN_RPC_URL}"
worldchain-sepolia = "${WORLDCHAIN_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
avalanche-fuji = "${AVALANCHE_FUJI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 1 }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
optimism = { key = "${ETHERSCAN_API_KEY}", chain = 10 }
optimism-sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155420 }
bsc = { key = "${ETHERSCAN_API_KEY}", chain = 56 }
bsc-testnet = { key = "${ETHERSCAN_API_KEY}", chain = 97 }
unichain = { key = "${ETHERSCAN_API_KEY}", chain = 130 }
unichain-sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 1301 }
polygon = { key = "${ETHERSCAN_API_KEY}", chain = 137 }
polygon-amoy = { key = "${ETHERSCAN_API_KEY}", chain = 80002 }
worldchain = { key = "${ETHERSCAN_API_KEY}", chain = 480 }
worldchain-sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 4801 }
base = { key = "${ETHERSCAN_API_KEY}", chain = 8453 }
base-sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 84532 }
arbitrum = { key = "${ETHERSCAN_API_KEY}", chain = 42161 }
arbitrum-sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 421614 }
avalanche = { key = "${ETHERSCAN_API_KEY}", chain = 43114 }
avalanche-fuji = { key = "${ETHERSCAN_API_KEY}", chain = 43113 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
